version: "3"
services:
  csvtocsvw:
    image: "ghcr.io/mat-o-lab/csvtocsvw:latest"
    container_name: "csvtocsvw"
    ports:
      - ${APP_PORT}:5000
    restart: always
    networks:
      - csvtocsvw_net
    environment:
      APP_MODE: "development"
      ADMIN_MAIL: ${ADMIN_MAIL}
    volumes:
      - ./:/src
    entrypoint: "python app.py"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/info"]
      interval: 10s
      timeout: 10s
      retries: 20

networks:
  csvtocsvw_net:
    name: csvtocsvw_net
    driver: bridge
